### ISSUE TITLE
multiple containers and config with same image

### ISSUE THREAD

**Issue by vijaykumarchettiar** [ned-kelly/docker-icecast-google-analytics#1]
Is it possible to run multiple containers and config with same docker-icecast-google-analytics ?

**Comment by iroks** [comment]
could you please explain your question more detailed?

**Comment by vijaykumarchettiar** [comment]
> could you please explain your question more detailed?

There are multiple icecast instances, so multiple docker config  and need to run multiple containers with unique id and point each container to different docker config file.
is that possible?

**Comment by iroks** [comment]
Multiple icecast instances, e.g. different servers, ok understand. but why you need multiple docker config and run multiple containers? could you please describe an application scenario?

**Comment by vijaykumarchettiar** [comment]
> Multiple icecast instances, e.g. different servers, ok understand. but why you need multiple docker config and run multiple containers? could you please describe an application scenario?

instead of using multiple server, i want to use the single server and run the docker with multiple config files.

**Comment by iroks** [comment]
is not the same? one config file with multiple server == multiple config files with one server? Just check if you can run multiple instances:
 docker-icecast-google-analytics/src/bootstrap.sh 

    java -jar /app/target/icecast2googleanalytics-1.0-SNAPSHOT-jar-with-dependencies.jar /config/config1.xml &
java -jar /app/target/icecast2googleanalytics-1.0-SNAPSHOT-jar-with-dependencies.jar /config/config2.xml &
    sleep 60

**Comment by vijaykumarchettiar** [comment]
> is not the same? one config file with multiple server == multiple config files with one server? Just check if you can run multiple instances:
> docker-icecast-google-analytics/src/bootstrap.sh
> 
> ```
> java -jar /app/target/icecast2googleanalytics-1.0-SNAPSHOT-jar-with-dependencies.jar /config/config1.xml &
> ```
> 
> java -jar /app/target/icecast2googleanalytics-1.0-SNAPSHOT-jar-with-dependencies.jar /config/config2.xml &
> sleep 60

thanks for the reply. let me check it.
